sudo: enabled
language: cpp
compiler:
  - gcc
env:
  global:
    - MAKEFLAGS="-j 4"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libboost-all-dev libcv-dev libopencv-dev libopencv-contrib-dev libopencv-gpu-dev libqt4-dev libqwt5-qt4-dev libqglviewer-dev cmake build-essential libfftw3-dev

install:
  - cp cedar.conf.example cedar.conf
  - mkdir build
  - cd build
  - cmake ..
  - make -j 4
  - make test
  - sudo make install
